### ISSUE TITLE
No Solr update on Move

### ISSUE THREAD

**Issue by tschechniker** [netgen/ezplatformsearch#11] opened 2016-11-09 10:53 UTC
Hi,

setup a Solr Search as descriped here https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle 

You will discover the following problem:

If you move an object via the legacy stack (for example move an object in the admin backend) the main location is not updated in the Solr index.

The problem is that ezcontentobjecttreenodeoperations.php is using a Database transaction. The reindex is triggered before the changes has been commited to the Database.

We have already created a Ticket in the eZ Systems Jira but because of this extension they closed it as "Won't fix": https://jira.ez.no/browse/EZP-26522

Best regards

**Comment by emodric** [comment] 2016-11-09 15:58
Hi @tschechniker!

Yes, this is the problem with eZ Publish legacy stack as you noticed, and I'm not sure that we can do anything here short of hacking the legacy kernel.

There is a workflow event that is triggered on content move, you can probably use that to trigger a reindex.

**Comment by vnivuahc** [comment] 2017-02-13 16:36
Hi, 

I face to a similar issue when I change the priority of sibling locations from the back-end.
In front, I use the SearchService to get all these locations, sorted by priority.
I can't get them in the right order until I reindex all contents manually (php ezpublish/console ezplatform:solr_create_index).

I don't really understand what is provided by your extension and what is part of the legacy kernel.
Maybe can you confirm that my issue is related with this one ? (If not I will open a ticket on the eZ System Jira.)

Best regards

**Comment by emodric** [comment] 2017-02-13 19:48
Hi @tschechniker 

This extension only works if eZ Publish Legacy kernel calls the reindexing process when certain events occur, like content copy, content edit and so on.

Unfortunatelly, eZ Publish Legacy does not call the reindexing process if, for example, location priority is updated, or calls it too early (before SQL transaction is completed) if content is moved. That is why the index is not updated when content is moved or location priority updated. Because of that, this is not something that can be fixed by this extension.

However, once (and if) eZ Systems implements such triggers in eZ Publish Legacy or modifies them to call the reindex process after SQL transactions are completed, reindexing would automatically start working with this extension.

**Comment by andrerom** [comment] 2017-02-20 11:26
@vnivuahc Could you try something ala _(apply in ezpublish_legacy)_:

```diff
diff --git a/kernel/content/ezcontentoperationcollection.php b/kernel/content/ezcontentoperationcollection.php
index 72167c6..24a23c2 100644
--- a/kernel/content/ezcontentoperationcollection.php
+++ b/kernel/content/ezcontentoperationcollection.php
@@ -736,6 +736,11 @@ class eZContentOperationCollection
 
        eZContentObject::fixReverseRelations( $objectID, 'move' );
 
+        if ( !eZSearch::getEngine() instanceof eZSearchEngine )
+        {
+            eZContentOperationCollection::registerSearchObject( $objectID );
+        }
+
        return array( 'status' => true );
     }
 
@@ -1214,12 +1219,20 @@ class eZContentOperationCollection
         $curNode = eZContentObjectTreeNode::fetch( $parentNodeID );
         if ( $curNode instanceof eZContentObjectTreeNode )
         {
+             $objectIDs = array();
              $db = eZDB::instance();
              $db->begin();
              for ( $i = 0, $l = count( $priorityArray ); $i < $l; $i++ )
              {
                  $priority = (int) $priorityArray[$i];
                  $nodeID = (int) $priorityIDArray[$i];
+                 $node = eZContentObjectTreeNode::fetch( $parentNodeID );
+                 if ( !$node instanceof eZContentObjectTreeNode )
+                 {
+                     continue;
+                 }
+
+                 $objectIDs[] = $node->attribute( 'contentobject_id' );
                  $db->query( "UPDATE
                                   ezcontentobject_tree
                               SET
@@ -1229,6 +1242,13 @@ class eZContentOperationCollection
              }
              $curNode->updateAndStoreModified();
              $db->commit();
+             if ( !eZSearch::getEngine() instanceof eZSearchEngine )
+             {
+                 foreach ( $objectIDs as $objectID )
+                 {
+                     eZContentOperationCollection::registerSearchObject( $objectID );
+                 }
+             }
         }
         return array( 'status' => true );
     }
```

**Comment by vnivuahc** [comment] 2017-02-21 09:47
@andrerom 

Thank you very much for this patch ! It works like a charm when moving a node.
But for the priority, I can't get it to work.

Also, I think there is a typo in your code. You add several times the same object ID in your array $objectIDs.
I tried to modify your code like this, but the indexing still does not work :

```diff
Index: kernel/content/ezcontentoperationcollection.php
--- kernel/content/ezcontentoperationcollection.php	(revision 2588)
+++ kernel/content/ezcontentoperationcollection.php	(revision )
@@ -736,6 +736,11 @@
 
        eZContentObject::fixReverseRelations( $objectID, 'move' );
 
+        if ( !eZSearch::getEngine() instanceof eZSearchEngine )
+        {
+            eZContentOperationCollection::registerSearchObject( $objectID );
+        }
+
        return array( 'status' => true );
     }
 
@@ -1214,12 +1219,20 @@
         $curNode = eZContentObjectTreeNode::fetch( $parentNodeID );
         if ( $curNode instanceof eZContentObjectTreeNode )
         {
+             $objectIDs = array();
              $db = eZDB::instance();
              $db->begin();
              for ( $i = 0, $l = count( $priorityArray ); $i < $l; $i++ )
              {
                  $priority = (int) $priorityArray[$i];
                  $nodeID = (int) $priorityIDArray[$i];
+                 $node = eZContentObjectTreeNode::fetch( $nodeID );
+                 if ( !$node instanceof eZContentObjectTreeNode )
+                 {
+                     continue;
+                 }
+
+                 $objectIDs[] = $node->attribute( 'contentobject_id' );
                  $db->query( "UPDATE
                                   ezcontentobject_tree
                               SET
@@ -1229,6 +1242,13 @@
              }
              $curNode->updateAndStoreModified();
              $db->commit();
+             if ( !eZSearch::getEngine() instanceof eZSearchEngine )
+             {
+                 foreach ( $objectIDs as $objectID )
+                 {
+                     eZContentOperationCollection::registerSearchObject( $objectID );
+                 }
+             }
         }
         return array( 'status' => true );
     }
```

**Comment by andrerom** [comment] 2017-02-21 10:40
yes `$node = eZContentObjectTreeNode::fetch( $nodeID );` is the correct one.
I don't think we need `$objectIDs = array( $curNode->attribute( 'contentobject_id' ) );` as index of parent technically does change afaik. 


As for why it is not working, could you verify if this is the code being called when you update priority? And what kind of data is being passed to `eZContentOperationCollection::registerSearchObject` if it is the right place?

**Comment by vnivuahc** [comment] 2017-02-21 15:02
Now everything is working (moving + priority)! : )

I followed these steps :
- `composer update` to get the last version of eZ Publish (v5.4.9)
- reindexing all content via the `php ezpublish/console --env=dev --siteaccess=site ezplatform:solr_create_index` command
- apply the modified patch (I edited it in my last post)

**Comment by andrerom** [comment] 2017-02-21 15:09
@vnivuahc great, I'll move forward on the patch them ;)

**Comment by emodric** [comment] 2017-02-21 15:12
@andrerom Do you think it would be good idea to migrate the patch to `ezsystems/ezpublish-legacy` ?

**Comment by andrerom** [comment] 2017-02-21 15:15
that is what I'm saying

**Comment by emodric** [comment] 2017-02-21 15:18
:+1:

**Comment by andrerom** [comment] 2017-03-07 20:34
@vnivuahc Apparently our QA and Support team has same issue you had at first here, they can't get the patch to work on first try. As in only every second update to priority seems to be indexed, sounds familiar? _See [issue](https://jira.ez.no/browse/EZP-27011?focusedCommentId=207384&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-207384) for more info._

@emodric Anything here or other places you might think of that can cause this btw?

**Comment by emodric** [comment] 2017-03-08 10:41
@andrerom No, not really. I don't see why first priority update would not be sent to Solr...

**Comment by vnivuahc** [comment] 2017-03-21 10:46
@andrerom Maybe you have to wait the cronjob :
`ezpublish/console --env=prod ezpublish:legacy:script runcronjobs.php ezplatformindexsubtree`

**Comment by andrerom** [comment] 2017-03-24 06:52
@vnivuahc Thanks for the suggestion, but apparently not the issue here (they tried).

**Comment by emodric** [comment] 2017-04-18 13:15
Closing as the issue is fixed in `ezsystems/ezpublish-legacy` (https://github.com/ezsystems/ezpublish-legacy/pull/1283)

**Closed as completed by emodric** 2017-04-18 13:15 UTC
